# ios/Podfile
platform :ios, '13.0'  # Đảm bảo phiên bản iOS tối thiểu là 13.0
use_frameworks!

# Thêm dòng này để tích hợp Flutter
flutter_application_path = '../..'
puts "Flutter application path: #{flutter_application_path}"
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  # Cài đặt các Flutter dependencies
  install_all_flutter_pods(flutter_application_path)
end