name: Deploy to Google Play

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build appbundle --release
      - uses: r0adkll/upload-google-play@v1
        with:
          service_account_json_content: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: 'hieutt.customer.app'
          release_files: build/app/outputs/bundle/release/app-release.aab
          track: 'internal' # or alpha, beta, production