name: Deploy to Google Play

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🛠️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: 📥 Install dependencies
        run: flutter pub get

      - name: 🌍 Generate localization files
        run: flutter gen-l10n

      - name: 🔑 Decode Keystore
        run: |
          mkdir -p android/app/
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: 🔑 Setup signing configs
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: 🔍 Debug Keystore & Signing Configs
        run: |
          ls -lah android/app/
          cat android/key.properties

      - name: 🚀 Build APK & AAB
        run: flutter build appbundle --release

      - name: 📤 Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: "hieutt.customer.app"
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
